#!/bin/bash

# Mate os processos existentes do MongoDB e Node.js
sudo pkill mongod
sudo pkill node

# Inicie e habilite o serviço MongoDB
sudo systemctl start mongod
sudo systemctl enable mongod

# Verifique o status do MongoDB
sudo systemctl status mongod

# Inicie o MongoDB com caminhos específicos em segundo plano
mongod --dbpath ~/data/db --logpath ~/data/log/mongodb/mongo.log --fork

# Inicie o Node.js com npm em segundo plano
npm run start &

# Confirmação
echo "MongoDB e Node.js foram reiniciados."